# Generated by Django 5.0.6 on 2024-06-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('account_no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('aadhar', models.IntegerField(max_length=12)),
                ('pincode', models.IntegerField(max_length=6)),
            ],
        ),
    ]
